# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: myJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo $(Build.SourcesDirectory)
  - script: 'ls -h'
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  
  - task: AzloadTest@1
    inputs:
      testname: 'cltTestdemo12'
      tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      TestPlan: 'valid.jmx'
      subscription: '7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a'
      loadTestRes: 'cloudtestres'
      resourcegroup: 'requestworkerdev'
      apikey: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNjMwNTYyMjk1LCJuYmYiOjE2MzA1NjIyOTUsImV4cCI6MTYzMDU2NjE5NSwiX2NsYWltX25hbWVzIjp7Imdyb3VwcyI6InNyYzEifSwiX2NsYWltX3NvdXJjZXMiOnsic3JjMSI6eyJlbmRwb2ludCI6Imh0dHBzOi8vZ3JhcGgud2luZG93cy5uZXQvNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3L3VzZXJzL2I0MmNjZGE3LWFiYWUtNGNkNi1hOWM4LTNjMzg0OTA2NDhlNy9nZXRNZW1iZXJPYmplY3RzIn19LCJhY3IiOiIxIiwiYWlvIjoiQVVRQXUvOFRBQUFBRHBXbnR1YmNRVWdjQk5RNDFVYTFPVDZVNEhyZXhoZGJ2YzlKT0xtK3ZmdDN6QTlQTllwcUxjekt4TlFQaEJ5Ujg0V214bU5DK3dONFdvOFdwOEJCK0E9PSIsImFtciI6WyJyc2EiLCJtZmEiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6IjkwODFhNDNkLTQ4ODMtNGQxZC05NWY3LWUwMzEwYTg0ZjQ1ZSIsImZhbWlseV9uYW1lIjoiS3VtYXJpIiwiZ2l2ZW5fbmFtZSI6IlN3ZXRhIiwiaXBhZGRyIjoiMTAzLjYxLjExMy43MSIsIm5hbWUiOiJTd2V0YSBLdW1hcmkiLCJvaWQiOiJiNDJjY2RhNy1hYmFlLTRjZDYtYTljOC0zYzM4NDkwNjQ4ZTciLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMjE0Njc3MzA4NS05MDMzNjMyODUtNzE5MzQ0NzA3LTI3MTQyMzkiLCJwdWlkIjoiMTAwMzIwMDEyRUVGQjZCMCIsInJoIjoiMC5BUm9BdjRqNWN2R0dyMEdScXkxODBCSGJSNVYzc0FUYmpScEd1LTRDLWVHX2UwWWFBSXcuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiSC1ob2E2UTVXTmlvUXJzaHJsb0RTaEJub280Q1pYUGN6TjFpVjdITHVSWSIsInRpZCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsInVuaXF1ZV9uYW1lIjoic3dldGFrdW1hcmlAbWljcm9zb2Z0LmNvbSIsInVwbiI6InN3ZXRha3VtYXJpQG1pY3Jvc29mdC5jb20iLCJ1dGkiOiJiNjdObV8tRHRrU3hQekd1T1NtUEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjEyODkyNDE1NDd9.mMlGy_nfxJA6d2oZODnHkKq7vRf8JaPSBOmItv-_yI2UvVDrl3IjLBhoBec3-somnC_cIp7s6D10gv0Qk2dp2bBQPS8Tu9dEdlptmvuH-9Mts4NTi7Ru23B5MbH9rgjvjf-6_EQYZwn2xmtJtKEnWysMfBIyJuK5x6ms3rOz47UR8C4HH-dCeSgyizB9CndeGvR2RKdbfMwOj_6J4F94uGSpIh_Nh_2VSzOkSVxQu462GQeW4YcdFZORM9fUgYUsYlwgPEWAJZaP-sEdh0zrdeG63oJnjCxfHmDEhutZMDJ5-lN1yHInab8JvmOLmpwhm6eimvgSfoyBHb7dTGkiOg'