# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12'
  displayName: 'Install Node.js'

- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'svcrwdev'
    YAMLFilePath: 'TmpFiles\loadTest.yaml'
    secrets: |
      [
         {
          "name": "secret",
          "value": "1797669089"
         }
      ]
    resourceGroup: 'abc-kc-rg'
    loadtestResource: 'krchanda'