# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12'
  displayName: 'Install Node.js'

- task: loadTest@1
  inputs:
    tenantId: '$(tenantId)'
    yamlFile: 'loadTest.yaml'
    subscription: '$(azureSubscription)'
    loadTestRes: 'cloudtestres'
    resourcegroup: 'requestworkerdev'
    monitor: |
      resoucreId1: sample resource1
      name: sampleName1,
       resoucreId2: sample resource2
      name: sampleName2
    apikey: '$(apikey)'