# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: myJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: extTask
  pool: 
    vmImage: 'ubuntu-latest' 
  steps:
  - task: AzloadTest@1
    inputs:
      testname: 'aztestdemo'
      tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      TestDrop: 'tmp'
      TestPlan: 'valid.jmx'
      subscription: '7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a'
      loadTestRes: 'cloudtestres'
      resourcegroup: 'requestworkerdev'
      apikey: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNjMwMjU1ODczLCJuYmYiOjE2MzAyNTU4NzMsImV4cCI6MTYzMDI1OTc3MywiX2NsYWltX25hbWVzIjp7Imdyb3VwcyI6InNyYzEifSwiX2NsYWltX3NvdXJjZXMiOnsic3JjMSI6eyJlbmRwb2ludCI6Imh0dHBzOi8vZ3JhcGgud2luZG93cy5uZXQvNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3L3VzZXJzL2I0MmNjZGE3LWFiYWUtNGNkNi1hOWM4LTNjMzg0OTA2NDhlNy9nZXRNZW1iZXJPYmplY3RzIn19LCJhY3IiOiIxIiwiYWlvIjoiQVVRQXUvOFRBQUFBejdxblpaTG45dmM5VFVudjNQLzFXeXZDQUoxaWRobDUzaFBXOGt3Y0Z3VW1BQlJjanlIYVorQkJ5Z1VNZG8vZGhRczlPZXA5cHlBazR4dm5xbnBFeEE9PSIsImFtciI6WyJyc2EiLCJtZmEiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6IjkwODFhNDNkLTQ4ODMtNGQxZC05NWY3LWUwMzEwYTg0ZjQ1ZSIsImZhbWlseV9uYW1lIjoiS3VtYXJpIiwiZ2l2ZW5fbmFtZSI6IlN3ZXRhIiwiaXBhZGRyIjoiMTEyLjE5Ni4xNjMuOTIiLCJuYW1lIjoiU3dldGEgS3VtYXJpIiwib2lkIjoiYjQyY2NkYTctYWJhZS00Y2Q2LWE5YzgtM2MzODQ5MDY0OGU3Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTIxNDY3NzMwODUtOTAzMzYzMjg1LTcxOTM0NDcwNy0yNzE0MjM5IiwicHVpZCI6IjEwMDMyMDAxMkVFRkI2QjAiLCJyaCI6IjAuQVJvQXY0ajVjdkdHcjBHUnF5MTgwQkhiUjVWM3NBVGJqUnBHdS00Qy1lR19lMFlhQUl3LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IkgtaG9hNlE1V05pb1Fyc2hybG9EU2hCbm9vNENaWFBjek4xaVY3SEx1UlkiLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJ1bmlxdWVfbmFtZSI6InN3ZXRha3VtYXJpQG1pY3Jvc29mdC5jb20iLCJ1cG4iOiJzd2V0YWt1bWFyaUBtaWNyb3NvZnQuY29tIiwidXRpIjoiUDl4TjRWZ1FZRVNOUnd5WFY4X0JBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc190Y2R0IjoxMjg5MjQxNTQ3fQ.KPYjmoBR0tGYdTKkSszwYfRgnCiOn3hXnGYzRzrEq94rjSseESsgIt1CRgSfIME_J4m1uZn34ypZNt13U_jv3QjyfU2Q-RamgvboVPHXkR3fH4Hg4KmIhNYHn_tTeTV4R3FcYSDQM2jOpcoW4QA86CePzXcLq1TClm-oUAtmmRab8jziILQG55yvhxpgQz4ML54srdBWEckb-gwtN4puS1fQqcxGFrXho3lJD_ojF5uhIGrWhqNb3W8b9a7dqabgV5W-LbN2WK6JJttU1hOIbxH80zBZ9OpDjtu8nIxYEnSApDYOXYfHMHVBiSoVK35b1ASI2U7IdddW4ZPeNnLXTA'